version: '3.8'

services:
  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cccat16
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/scripts/:/docker-entrypoint-initdb.d/
