version: '3.8'

services:
  app:
    container_name: app
    build: .
    restart: always
    command: bash -c "yarn install --only=prod && npm run debug"
    environment:
      ABC: text
    env_file:
      - .env
    volumes:
      - .:/home/node/app
      - ./dist/:/home/node/app/dist
#      - ./package.json:/home/node/app/package.json
    ports:
      - "3000:3000"
    networks:
      - cccat_16_node

  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cccat16
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/scripts/:/docker-entrypoint-initdb.d/
    networks:
      - cccat_16_node

networks:
  cccat_16_node:
    driver: bridge
